### ISSUE TITLE
Create a website template

### ISSUE THREAD

**Issue by Twanawebtech** [DevCenterHouse/massimosgrill.ie#1]
- [ ] Create a website, copy the current content from here: http://massimosrestaurant.ie on to the new website.

Copy everything except the 2nd restaurant details (Ashbourne). 
Do not copy the Ashbourne details. 

We will just use them below: 

Dunshaughlin
Unit 1, An Sibin Court
Main street
Dunshaughlin Co. Meath

Telephone: 01 824 1877
Email: eat@massimosrestaurant.ie

----

- [ ] For the logo, use Massimos Grill. Or leave it as it is.

**Comment by mdejuan** [comment]
@Twanawebtech code for most of the changes is in repo;
There are things to fix like the menu for drinks, maybe the map, etc
