### ISSUE TITLE
Find top 3 templates for the new site

### ISSUE THREAD

**Issue by Twanawebtech** [DevCenterHouse/massimosgrill.ie#2]
Find top 3 templates for the new site

**Comment by mdejuan** [comment]
These are the templates that, from my point of view, could suit (most of them has different home pages ):

1. This is quite simple, maybe the menu part is not enough...
https://elements.envato.com/tasty-restaurant-html-template-8GP9X2?_ga=2.151257021.505712460.1560419109-448333141.1560419109


2. This one has a cool dark stile in home page, and a display menu with detail page that could be interesting ... Mobile version for menu also ok.
https://themeforest.net/item/chocolat-bootstrap-restaurant-template/11151366?_ga=2.36886436.505712460.1560419109-448333141.1560419109

http://ignitethemes.net/chocolat/index-2.html


More:

http://preview.themeforest.net/item/luxury-simple-restaurant-parallax-full-screen-one-page-responsive-html5css3-template-design/full_screen_preview/21402760?ref=blueberry1

https://demo.web3canvas.com/themeforest/tomato/index.html

http://preview.themeforest.net/item/steak-in-restaurant-cafe-html5-template/full_screen_preview/20750451?ref=blueberry1
